github:
  history_count: 30
  api:
    base_url: 'https://api.github.com'
    organization: 'yourorg'
    concurrency: 15
  services:

kubernetes:
  argo:
    selector: 
  service:
    selector:
      - role: [stable]
    filter:
      # - service-a
      # - service-b

